### ISSUE TITLE
You need padding in the footer in "Conclusion"

### ISSUE THREAD

**Issue by PatheticMustan** [KryptoCrash/EnglishProjectReactApp#1]
![aff4c53d-90a1-4f8d-a037-a39665776aec](https://user-images.githubusercontent.com/35382971/52214397-84692c00-285f-11e9-81a4-29c0ac3a8455.png)
Pls add padding, or margin, they'll both work the same way in this instance.

**Comment by KryptoCrash** [comment]
fixed in commit #0fe281e
